
package calculator;
import javax.swing.*;
/**
 *
 * @author abdul karim
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Calculator = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        Display = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        btnprs = new javax.swing.JButton();
        btnAc = new javax.swing.JButton();
        btnroot = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnequal = new javax.swing.JButton();
        BtnMplus = new javax.swing.JButton();
        btnMsub = new javax.swing.JButton();
        btnMr = new javax.swing.JButton();
        btnMc = new javax.swing.JButton();
        btnsqr = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        btnml = new javax.swing.JButton();
        btnsub = new javax.swing.JButton();
        btnplus = new javax.swing.JButton();
        Display2 = new javax.swing.JTextField();
        btnSin = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnCot = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        btn3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jPanel4 = new javax.swing.JPanel();

        Calculator.setAlignment(java.awt.Label.CENTER);
        Calculator.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        Calculator.setName(""); // NOI18N
        Calculator.setPreferredSize(new java.awt.Dimension(45, 40));
        Calculator.setText("Calculator");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBounds(new java.awt.Rectangle(200, 70, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(406, 476));
        setMinimumSize(new java.awt.Dimension(406, 476));
        setName("MainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(406, 476));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 4, 2, new java.awt.Color(0, 255, 153)));
        jPanel1.setForeground(new java.awt.Color(51, 204, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(410, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(410, 450));
        jPanel1.setName("MainPanel"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(410, 450));
        jPanel1.setLayout(null);

        Display.setBackground(new java.awt.Color(74, 112, 77));
        Display.setForeground(new java.awt.Color(0, 0, 0));
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display.setToolTipText("");
        Display.setAlignmentX(3.0F);
        Display.setAlignmentY(2.0F);
        Display.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 0, 4, new java.awt.Color(0, 102, 102)));
        Display.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Display.setMaximumSize(new java.awt.Dimension(450, 50));
        Display.setMinimumSize(new java.awt.Dimension(450, 19));
        Display.setName(""); // NOI18N
        Display.setPreferredSize(new java.awt.Dimension(450, 19));
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });
        jPanel1.add(Display);
        Display.setBounds(20, 59, 360, 30);

        btnback.setText("←");
        btnback.setToolTipText("");
        btnback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnback.setPreferredSize(new java.awt.Dimension(30, 30));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);
        btnback.setBounds(330, 180, 50, 30);

        btnprs.setBackground(new java.awt.Color(128, 214, 214));
        btnprs.setForeground(new java.awt.Color(51, 51, 0));
        btnprs.setText("%");
        btnprs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprs.setPreferredSize(new java.awt.Dimension(30, 30));
        btnprs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprsActionPerformed(evt);
            }
        });
        jPanel1.add(btnprs);
        btnprs.setBounds(30, 380, 50, 30);

        btnAc.setBackground(new java.awt.Color(255, 0, 51));
        btnAc.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnAc.setText("AC");
        btnAc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAc.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAc.setPreferredSize(new java.awt.Dimension(30, 30));
        btnAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcActionPerformed(evt);
            }
        });
        jPanel1.add(btnAc);
        btnAc.setBounds(30, 180, 50, 30);

        btnroot.setBackground(new java.awt.Color(128, 214, 214));
        btnroot.setForeground(new java.awt.Color(51, 51, 0));
        btnroot.setText("√");
        btnroot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnroot.setPreferredSize(new java.awt.Dimension(30, 30));
        btnroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrootActionPerformed(evt);
            }
        });
        jPanel1.add(btnroot);
        btnroot.setBounds(30, 340, 50, 30);

        btn7.setBackground(new java.awt.Color(153, 153, 255));
        btn7.setText("7");
        btn7.setPreferredSize(new java.awt.Dimension(30, 30));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);
        btn7.setBounds(100, 260, 50, 30);

        btn4.setBackground(new java.awt.Color(153, 153, 255));
        btn4.setText("4");
        btn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn4.setPreferredSize(new java.awt.Dimension(30, 30));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);
        btn4.setBounds(100, 300, 50, 30);

        btn1.setBackground(new java.awt.Color(153, 153, 255));
        btn1.setText("1");
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.setPreferredSize(new java.awt.Dimension(30, 30));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);
        btn1.setBounds(100, 340, 50, 30);

        btn0.setBackground(new java.awt.Color(153, 153, 255));
        btn0.setText("0");
        btn0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn0.setPreferredSize(new java.awt.Dimension(30, 30));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0);
        btn0.setBounds(100, 380, 50, 30);

        btndot.setBackground(new java.awt.Color(153, 153, 255));
        btndot.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btndot.setText(".");
        btndot.setPreferredSize(new java.awt.Dimension(30, 30));
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });
        jPanel1.add(btndot);
        btndot.setBounds(170, 380, 56, 30);

        btn2.setBackground(new java.awt.Color(153, 153, 255));
        btn2.setText("2");
        btn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2.setPreferredSize(new java.awt.Dimension(30, 30));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);
        btn2.setBounds(170, 340, 56, 30);

        btn5.setBackground(new java.awt.Color(153, 153, 255));
        btn5.setText("5");
        btn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn5.setPreferredSize(new java.awt.Dimension(30, 30));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);
        btn5.setBounds(170, 300, 56, 30);

        btn8.setBackground(new java.awt.Color(153, 153, 255));
        btn8.setText("8");
        btn8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn8.setPreferredSize(new java.awt.Dimension(30, 30));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);
        btn8.setBounds(170, 260, 56, 30);

        btn9.setBackground(new java.awt.Color(153, 153, 255));
        btn9.setText("9");
        btn9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn9.setPreferredSize(new java.awt.Dimension(30, 30));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);
        btn9.setBounds(250, 260, 60, 30);

        btn6.setBackground(new java.awt.Color(153, 153, 255));
        btn6.setText("6");
        btn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn6.setPreferredSize(new java.awt.Dimension(30, 30));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);
        btn6.setBounds(250, 300, 60, 30);

        btnequal.setBackground(new java.awt.Color(51, 51, 255));
        btnequal.setText("=");
        btnequal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnequal.setPreferredSize(new java.awt.Dimension(30, 30));
        btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalActionPerformed(evt);
            }
        });
        jPanel1.add(btnequal);
        btnequal.setBounds(250, 380, 60, 30);

        BtnMplus.setBackground(new java.awt.Color(128, 214, 214));
        BtnMplus.setForeground(new java.awt.Color(51, 51, 0));
        BtnMplus.setText("M+");
        BtnMplus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMplus.setPreferredSize(new java.awt.Dimension(30, 30));
        BtnMplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMplusActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMplus);
        BtnMplus.setBounds(30, 300, 50, 30);

        btnMsub.setBackground(new java.awt.Color(128, 214, 214));
        btnMsub.setForeground(new java.awt.Color(51, 51, 0));
        btnMsub.setText("M-");
        btnMsub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMsub.setPreferredSize(new java.awt.Dimension(30, 30));
        btnMsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsubActionPerformed(evt);
            }
        });
        jPanel1.add(btnMsub);
        btnMsub.setBounds(30, 260, 46, 30);

        btnMr.setText("MR");
        btnMr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMr.setPreferredSize(new java.awt.Dimension(30, 30));
        btnMr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMrActionPerformed(evt);
            }
        });
        jPanel1.add(btnMr);
        btnMr.setBounds(100, 180, 50, 30);

        btnMc.setText("MC");
        btnMc.setPreferredSize(new java.awt.Dimension(30, 30));
        btnMc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMcActionPerformed(evt);
            }
        });
        jPanel1.add(btnMc);
        btnMc.setBounds(170, 180, 50, 30);

        btnsqr.setText("x^2 ");
        btnsqr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsqr.setPreferredSize(new java.awt.Dimension(60, 45));
        btnsqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsqrActionPerformed(evt);
            }
        });
        jPanel1.add(btnsqr);
        btnsqr.setBounds(250, 180, 56, 29);

        btndiv.setBackground(new java.awt.Color(128, 214, 214));
        btndiv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btndiv.setForeground(new java.awt.Color(51, 51, 0));
        btndiv.setText("/");
        btndiv.setPreferredSize(new java.awt.Dimension(60, 45));
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });
        jPanel1.add(btndiv);
        btndiv.setBounds(330, 260, 50, 30);

        btnml.setBackground(new java.awt.Color(128, 214, 214));
        btnml.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnml.setForeground(new java.awt.Color(51, 51, 0));
        btnml.setText("*");
        btnml.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnml.setPreferredSize(new java.awt.Dimension(60, 45));
        btnml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmlActionPerformed(evt);
            }
        });
        jPanel1.add(btnml);
        btnml.setBounds(330, 300, 50, 31);

        btnsub.setBackground(new java.awt.Color(128, 214, 214));
        btnsub.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnsub.setForeground(new java.awt.Color(51, 51, 0));
        btnsub.setText("-");
        btnsub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsub.setPreferredSize(new java.awt.Dimension(60, 45));
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubActionPerformed(evt);
            }
        });
        jPanel1.add(btnsub);
        btnsub.setBounds(330, 340, 50, 30);

        btnplus.setBackground(new java.awt.Color(128, 214, 214));
        btnplus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnplus.setForeground(new java.awt.Color(51, 51, 0));
        btnplus.setText("+");
        btnplus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnplus.setPreferredSize(new java.awt.Dimension(60, 45));
        btnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplusActionPerformed(evt);
            }
        });
        jPanel1.add(btnplus);
        btnplus.setBounds(330, 380, 50, 31);

        Display2.setEditable(false);
        Display2.setBackground(new java.awt.Color(74, 112, 77));
        Display2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Display2.setForeground(new java.awt.Color(0, 0, 0));
        Display2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 4, 4, new java.awt.Color(0, 102, 102)));
        jPanel1.add(Display2);
        Display2.setBounds(20, 84, 360, 30);

        btnSin.setBackground(new java.awt.Color(128, 214, 214));
        btnSin.setForeground(new java.awt.Color(51, 51, 0));
        btnSin.setText("sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });
        jPanel1.add(btnSin);
        btnSin.setBounds(330, 220, 50, 30);

        btnCos.setBackground(new java.awt.Color(128, 214, 214));
        btnCos.setForeground(new java.awt.Color(51, 51, 0));
        btnCos.setText("cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCos);
        btnCos.setBounds(250, 220, 60, 30);

        btnTan.setBackground(new java.awt.Color(128, 214, 214));
        btnTan.setForeground(new java.awt.Color(51, 51, 0));
        btnTan.setText("tan");
        btnTan.setMaximumSize(new java.awt.Dimension(52, 25));
        btnTan.setMinimumSize(new java.awt.Dimension(52, 25));
        btnTan.setPreferredSize(new java.awt.Dimension(52, 25));
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });
        jPanel1.add(btnTan);
        btnTan.setBounds(170, 220, 50, 30);

        btnCot.setBackground(new java.awt.Color(128, 214, 214));
        btnCot.setForeground(new java.awt.Color(51, 51, 0));
        btnCot.setText("cot");
        btnCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotActionPerformed(evt);
            }
        });
        jPanel1.add(btnCot);
        btnCot.setBounds(100, 220, 50, 30);

        btnlog.setBackground(new java.awt.Color(128, 214, 214));
        btnlog.setForeground(new java.awt.Color(51, 51, 0));
        btnlog.setText("log");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        jPanel1.add(btnlog);
        btnlog.setBounds(30, 220, 50, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true)));
        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 40, 380, 90);
        jPanel1.add(jLayeredPane1);
        jLayeredPane1.setBounds(180, 380, 0, 0);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 3, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102))));
        jPanel1.add(jLayeredPane2);
        jLayeredPane2.setBounds(0, 420, 30, 30);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 3, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102))));
        jPanel1.add(jLayeredPane3);
        jLayeredPane3.setBounds(370, 420, 30, 30);

        btn3.setBackground(new java.awt.Color(153, 153, 255));
        btn3.setText("3");
        btn3.setPreferredSize(new java.awt.Dimension(30, 30));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);
        btn3.setBounds(250, 340, 60, 30);

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 0, 0, 0, new java.awt.Color(204, 255, 204)));

        jTextField1.setBackground(new java.awt.Color(0, 51, 51));
        jTextField1.setFont(new java.awt.Font("Felix Titling", 2, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Md. Abdul Karim");
        jTextField1.setBorder(null);
        jPanel3.add(jTextField1);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 420, 400, 30);

        jLayeredPane4.setBackground(new java.awt.Color(0, 51, 51));
        jLayeredPane4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 3, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(jLayeredPane4);
        jLayeredPane4.setBounds(360, -1, 40, 30);

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 3, true), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102))));
        jPanel1.add(jLayeredPane5);
        jLayeredPane5.setBounds(-1, 0, 40, 30);

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(204, 255, 204)));
        jPanel4.setToolTipText("");
        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 400, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        s=s+"0";
        Display.setText(s);
        
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        s=s+"7";
        Display.setText(s);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        s=s+"1";
        Display.setText(s);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        s=s+"2";
        Display.setText(s);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        s=s+"4";
        Display.setText(s);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        s=s+"5";
        Display.setText(s);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        s=s+"6";
        Display.setText(s);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        s=s+"8";
        Display.setText(s);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        s=s+"9";
        Display.setText(s);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
        if(s.length() !=0){
        s=s+".";
        Display.setText(s);
        }
    }//GEN-LAST:event_btndotActionPerformed

    private void btnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusActionPerformed
        if(value !=0){
            s=Double.toString(value) +"+";
            Display.setText(s);
        }
        else if(s.length() !=0){
        s=s+"+";
        Display.setText(s);
        }
    }//GEN-LAST:event_btnplusActionPerformed

    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed
        if(value !=0){
            s=Double.toString(value) +"-";
            Display.setText(s);
        }
        else if(s.length() !=0){
        s=s+"-";
        Display.setText(s);
        }
    }//GEN-LAST:event_btnsubActionPerformed

    private void btnmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmlActionPerformed
        if(value !=0){
            s=Double.toString(value) +"*";
            Display.setText(s);
        }
        else if(s.length() !=0){
        s=s+"*";
        Display.setText(s);
        }
    }//GEN-LAST:event_btnmlActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
        if(value !=0){
            s=Double.toString(value) +"/";
            Display.setText(s);
        }
        else if(s.length() !=0){
        s=s+"/";
        Display.setText(s);
        }
    }//GEN-LAST:event_btndivActionPerformed

    private void btnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalActionPerformed
        
        if(s.length()>0){   
        String w[]=s.split("\\+|-|\\*|/|%");
        String[] x = s.split("(?<=[-+*/])|(?=[-+*/])");

        double result=0;
        try{
            for (String w1 : w) {
                if (s.contains("*")) {
                    if (result ==0) {
                        result = (double) Double.parseDouble(w1);
                    } else {
                        result *= (double) Double.parseDouble(w1);
                    }
                    result=Math.round(result*100)/100.0;
                    Display2.setText(Double.toString(result));
                }if (s.contains("/")) {
                    if (result ==0) {
                        result = (double) Double.parseDouble(w1);
                    } else if(Double.parseDouble(w1)!=0){
                        //if(Double.parseDouble(w[i+1])!=0){
                        result /= (double) Double.parseDouble(w1);
                        result=Math.round(result*100)/100.0;
                        //Display.setText(double.toString(a*b));
                        Display2.setText(Double.toString(result));
                    }else
                    {
                       Display.setText("Math Error");
                       break;
                    }
                }if (s.contains("+")) {
                    result += (double) Double.parseDouble(w1);
                    result=Math.round(result*100)/100.0;
                    Display2.setText(Double.toString(result));
                }if (s.contains("-")) {
                    if (result ==0) {
                        result = (double) Double.parseDouble(w1);
                    } else {
                        result -= (double) Double.parseDouble(w1);
                    }
                    result=Math.round(result*100)/100.0;
                    Display2.setText(Double.toString(result));
                } 
            }
            }catch(NumberFormatException e){
                Display.setText("Syntax Error");
                s=new String();
                Display2.setText(s);
            }
        
        if(result != 0){
            value=result;
        }
        }
        s=new String();
    }//GEN-LAST:event_btnequalActionPerformed

    private void btnAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcActionPerformed
        s=new String();
        value =0;
        Display.setText(s);
        Display2.setText(s);
    }//GEN-LAST:event_btnAcActionPerformed

    private void btnprsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprsActionPerformed
        if(s.length()>0){
        s=s+"%";
        Display.setText(s);
        //double b=0;
        String w[]=s.split("\\+|-|\\*|/|%");
        double result=0;
        double p=100;
        int flage=0;
        if(w.length < 2){
            result=Double.parseDouble(w[0]);
            Display2.setText(Double.toString(result));
        }else if(w.length > 2){
            Display.setText("Syntax Error");
        }else if(w.length > 1){
            double a=Double.parseDouble(w[0]);
            double b=Double.parseDouble(w[1]);
        if(s.contains("+"))
        {
            
            if(Double.parseDouble(w[1])!=0){
                
                result=(double)((a+b)*p)/b;
                result=Math.round(result*100)/100.0;
                Display2.setText(Double.toString(result));
          }else
            {
                Display.setText("Math Error");
            }
        }else if(s.contains("-")){
            
            if(b!=0){
                result=(double)((a-b)*p)/b;
                result=Math.round(result*100)/100.0;
                Display2.setText(Double.toString(result));
            }else
            {
                Display.setText("Math Error");
            }
        }else if(s.contains("*")){
            
            result=(double)a*(b/p);
            result=Math.round(result*100)/100.0;
            Display2.setText(Double.toString(result));
            
        }else if(s.contains("/")){
            
            if(b!=0){
                result=(double)a*p/b;
                result=Math.round(result*100)/100.0;
                Display2.setText(Double.toString(result));
            }else
            {
                Display.setText("Math Error");
            } 
        }
        
        }
        if(result != 0){
            value=result;
        }
        
        }
    }//GEN-LAST:event_btnprsActionPerformed

    private void btnrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrootActionPerformed
       if(s.length()>0 || value !=0){
        double result=0;
        if(value == 0){
           result=Double.parseDouble(s);
           //Display.setText(Double.toString(result));
           Display.setText("√"+s);
           result=(double)Math.sqrt(result);
        
           result=Math.round(result*100)/100.0;
           Display2.setText(Double.toString(result)); 
        }else{
           s=Double.toString(value);
           Display.setText("√"+s);
           result=(double)Math.sqrt(value);
        
           result=Math.round(result*100)/100.0;
           Display2.setText(Double.toString(result));
        }
        if(result != 0){
            value=result;
        }
       }
        
        //s=new String();
    }//GEN-LAST:event_btnrootActionPerformed
    
    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        
//int i=(s.length());
        String front = s.substring(0, s.length()-1);
        s= front;
        Display.setText(s);
        
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnMrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMrActionPerformed
        
        if(value != 0){
            Display2.setText(s);
            m=Double.toString(value);
            s=new String();
            Display.setText(m);
        }
        
    }//GEN-LAST:event_btnMrActionPerformed

    private void BtnMplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMplusActionPerformed
        if(value !=0){
            s=new String();
            s=Double.toString(value);
            //s=m+"+"+s;
            Display.setText(m+"+"+s);
            double result=0;
            result=Double.parseDouble(m);
            result=result+value;
            
            Display2.setText(Double.toString(result));
            if(result != 0){
                value=result;
            }
        }
        value=0;
    }//GEN-LAST:event_BtnMplusActionPerformed

    private void btnMsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsubActionPerformed
        if(value !=0){
            s=new String();
            s=Double.toString(value);
            //s=m+"+"+s;
            Display.setText(m+"+"+s);
            double result=0;
            result=Double.parseDouble(m);
            result=result-value;
            
            Display2.setText(Double.toString(result));
            if(result != 0){
                value=result;
            }
        }
        value=0;
    }//GEN-LAST:event_btnMsubActionPerformed

    private void btnMcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMcActionPerformed
        if(m != null){
            Display.setText("Memory Clear");
            
        }else{
            Display.setText("Memory is Empty");
        }
        
        m=new String();
        s=new String();
        Display2.setText(s);
        m=null;
        
    }//GEN-LAST:event_btnMcActionPerformed

    private void btnsqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsqrActionPerformed
        
        double result=0;
        if(s.length()>0 || value !=0){
        if(value == 0){
           result=Double.parseDouble(s);
           //Display.setText(Double.toString(result));
           Display.setText(s+"^"+"2");
           result=(double)(result*result);
        
           result=Math.round(result*100)/100.0;
           Display2.setText(Double.toString(result)); 
        }else{
           s=Double.toString(value);
           Display.setText(s+"^"+"2");
           result=(double)(value*value);
        
           result=Math.round(result*100)/100.0;
           Display2.setText(Double.toString(result));
        }
        }
        if(result != 0){
            value=result;
        }
        
    }//GEN-LAST:event_btnsqrActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
       
        double result=0;
        if(s.length()>0 || value !=0){
        if(value == 0){
           result=Double.parseDouble(s);
           //Display.setText(Double.toString(result));
           Display.setText("sin"+"("+s+")");
           result=Math.sin(Math.toRadians(result));
        
           result=Math.round(result*100)/100.0;
           Display2.setText(Double.toString(result)); 
        }else{
           s=Double.toString(value);
           Display.setText("sin"+"("+s+")");
           result=Math.sin(Math.toRadians(value));
        
           result=Math.round(result*100)/100.0;
           Display2.setText(Double.toString(result));
        }
        }
        if(result != 0){
            value=result;
        }
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        double result=0;
        if(s.length()>0 || value !=0){
        if(value == 0){
           result=Double.parseDouble(s);
           //Display.setText(Double.toString(result));
           Display.setText("cos"+"("+s+")");
           result=Math.cos(Math.toRadians(result));
        
           result=Math.round(result*100)/100.0;
           Display2.setText(Double.toString(result)); 
        }else{
           s=Double.toString(value);
           Display.setText("cos"+"("+s+")");
           result=Math.cos(Math.toRadians(value));
        
           result=Math.round(result*100)/100.0;
           Display2.setText(Double.toString(result));
        }
        }
        if(result != 0){
            value=result;
        }
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        double result=0;
        if(s.length()>0 || value !=0){
        if(value == 0){
           result=Double.parseDouble(s);
           
           Display.setText("tan"+"("+s+")");
           
           double result1=Math.sin(Math.toRadians(result));
           double result2=Math.cos(Math.toRadians(result));
           if(result2 != 0){
               result=result1/result2;
               result=Math.round(result*100)/100.0;
               Display2.setText(Double.toString(result));
           }else if(result2 ==0){
               Display.setText("Math Error");
           }
                    
        }else{
           s=Double.toString(value);
           Display.setText("tan"+"("+s+")");
        
           double result1=Math.sin(Math.toRadians(value));
           double result2=Math.cos(Math.toRadians(value));
           if(result2 !=0){
               result=result1/result2;
               result=Math.round(result*100)/100.0;
               Display2.setText(Double.toString(result));
           }else if(result2 ==0){
               Display.setText("Math Error");
           }
        }
        }
        if(result != 0){
            value=result;
        }
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotActionPerformed
        double result=0;
        if(s.length()>0 || value !=0){
        if(value == 0){
           result=Double.parseDouble(s);
           //Display.setText(Double.toString(result));
           Display.setText("cot"+"("+s+")");
           //result=Math.cot(Math.toRadians(result));
           double result1=Math.sin(Math.toRadians(result));
           double result2=Math.cos(Math.toRadians(result));
           if(result1 != 0){
               result=result2/result1;
               result=Math.round(result*100)/100.0;
               Display2.setText(Double.toString(result));
           }else{
               Display.setText("Math Error");
           }
                    
        }else{
           s=Double.toString(value);
           Display.setText("cot"+"("+s+")");
        
           double result1=Math.sin(Math.toRadians(value));
           double result2=Math.cos(Math.toRadians(value));
           if(result1 !=0){
               result=result2/result1;
               result=Math.round(result*100)/100.0;
               Display2.setText(Double.toString(result));
           }else{
               Display.setText("Math Error");
           }
        }
        }
        if(result != 0){
            value=result;
        }
    }//GEN-LAST:event_btnCotActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        double result=0;
        if(s.length()>0 || value !=0){
        if(value == 0){
           result=Double.parseDouble(s);
           //Display.setText(Double.toString(result));
           Display.setText("log"+"("+s+")");
           result=Math.log(result);
        
           result=Math.round(result*100)/100.0;
           Display2.setText(Double.toString(result)); 
        }else{
           s=Double.toString(value);
           Display.setText("log"+"("+s+")");
           result=Math.log(value);
        
           result=Math.round(result*100)/100.0;
           Display2.setText(Double.toString(result));
        }
    }
       
        if(result != 0){
            value=result;
        }
    }//GEN-LAST:event_btnlogActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        s=s+"3";
        Display.setText(s);
    }//GEN-LAST:event_btn3ActionPerformed

    public String s=new String();
    public String m=new String();
    public double value;
    
    
    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(() -> {
            new Calculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMplus;
    private java.awt.Label Calculator;
    private javax.swing.JTextField Display;
    private javax.swing.JTextField Display2;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAc;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnCot;
    private javax.swing.JButton btnMc;
    private javax.swing.JButton btnMr;
    private javax.swing.JButton btnMsub;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btndot;
    private javax.swing.JButton btnequal;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnml;
    private javax.swing.JButton btnplus;
    private javax.swing.JButton btnprs;
    private javax.swing.JButton btnroot;
    private javax.swing.JButton btnsqr;
    private javax.swing.JButton btnsub;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
